import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import {Inter, Source_Sans_3} from "next/font/google"


const inter = Inter(
  {
    subsets: ["latin"],
    variable: "--font-inter",
  }
);
const sourceSans3 = Source_Sans_3(
  {
    subsets: ["latin"],
    variable: "--font-source-sans-3",
  }
  
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${
          inter.variable} ${inter.className} ${sourceSans3.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
